# Required to run your project under the correct environment.
language: php

# Versions of PHP you want your project run with.
php:
  - 5.5
  - 5.6
  - 7.0

# Commands to be run before your environment runs.
before_script:
  - composer self-update
  - composer install --prefer-source --no-interaction

# Commands you want to run that will verify your build.
script:
  - mkdir -p build/logs
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

# allow_failures: Allow this build to fail under the specified environments.
# fast_finish: If your build fails do not continue trying to build, just stop.
matrix:
  fast_finish: true
  allow_failures:
    - php: 5.5

# Customize when the notification emails are sent.
notifications:
    on_success: never
    on_failure: always

after_success:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;'
